# Generated by Django 3.2.7 on 2022-01-28 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_post_categories'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='konum',
            field=models.CharField(default='', max_length=100),
        ),
    ]
